version: '3.7'

services:
    ldap:
        # image: linagora/linshare-ldap-for-tests:1.0
        build: .
        container_name: linshare_ldap_build
        tty: true
        stdin_open: true
        ports:
          - 21389:389
        environment:
          - LDAP_LOG_LEVEL=256
          - CONTAINER_LOG_LEVEL=4
        command: --copy-service --loglevel debug
#       volumes:
#         - ./data.ldif:/container/service/slapd/assets/config/bootstrap/ldif/linshare.ldif
